# A local development starters kit for the Supabase CLI

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions]
verify_jwt = false

[functions.create-abacatepay-pix]
verify_jwt = false

[functions.abacatepay-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"